export default {
  'SEARCH_PRODUCTS': 'SEARCH_PRODUCTS',
  'SEARCH_TERM': 'SEARCH_TERM',
  'FETCH_COUNTRIES': 'FETCH_COUNTRIES',
  'REDIRECT_TO_HOME': 'REDIRECT_TO_HOME',
  'SORT_PRODUCTS': 'SORT_PRODUCTS',
  'ADD_COUNTRY_FILTER': 'ADD_COUNTRY_FILTER',
  'ADD_PRICE_FILTER': 'ADD_PRICE_FILTER',
  'REMOVE_COUNTRY_FILTER': 'REMOVE_COUNTRY_FILTER',
  'REMOVE_PRICE_FILTER': 'REMOVE_PRICE_FILTER',
  'INIT_AGGREGATION': 'INIT_AGGREGATION',
  'CURRENT_SEARCH_PAGE': 'CURRENT_SEARCH_PAGE'
}