export default {
  'SEARCH_PRODUCTS': 'SEARCH_PRODUCTS',
  'SEARCH_TERM': 'SEARCH_TERM',
  'FETCH_COUNTRIES': 'FETCH_COUNTRIES',
  'REDIRECT_TO_HOME': 'REDIRECT_TO_HOME',
  'SORT_PRODUCTS': 'SORT_PRODUCTS',
  'FILTER_PRODUCTS': 'FILTER_PRODUCTS',
  'INIT_AGGREGATION': 'INIT_AGGREGATION'
}